const scenes=[
 ['空白','最后一笔，不在纸上。','白布只画了一半。裂开的空白像一道门，木桌后的山正等着你。'],
 ['入山','布的褶皱，长成了山。','蜡线无法接上的地方抬起成山脊，靛蓝染料沿纤维流成溪谷。'],
 ['相遇','山野教你八种线。','花生长，藤蔓连接，溪水流动，鱼回旋，蝶翼不对称，古树重复，村寨守护，鸟指向归途。'],
 ['失控','风把记忆吹散。','纸页脱手，纹样碎片卷入蓝色风暴。你只能追着鸟群穿过山谷和云层。'],
 ['选择','这一半，该由你来画。','回到木桌，把主纹、连接与节奏重新组合。留下呼吸，而不是复制外婆。'],
 ['归途','山野，穿在了身上。','纹样从衣服漫向河流、树木和天空。远处是外婆模糊的背影，近处是你自己的线。']
];
const labels=['花','藤','水','鱼','蝶','树','寨','鸟'];
const root=document.createElement('section');root.className='cinematic';root.dataset.act='0';root.setAttribute('aria-label','六幕完整故事');root.innerHTML=`<canvas aria-hidden="true"></canvas><button class="cinematic-close" aria-label="退出完整故事">退出 ×</button><div class="memory-orbit"></div><div class="choice-strip">${['花 · 主纹','藤蔓 · 连接','年轮 · 节奏'].map((x,i)=>`<button aria-pressed="${i===0}">${x}</button>`).join('')}</div><div class="cinematic-ui"><div class="cinematic-copy"><div class="cinematic-count"></div><h2></h2><p></p><div class="cinematic-actions"><button class="cinematic-back">上一幕</button><button class="cinematic-next">进入下一幕</button></div></div></div><i class="cinematic-flash"></i>`;document.body.append(root);
const canvas=root.querySelector('canvas'),ctx=canvas.getContext('2d'),count=root.querySelector('.cinematic-count'),title=root.querySelector('h2'),copy=root.querySelector('.cinematic-copy p'),next=root.querySelector('.cinematic-next'),back=root.querySelector('.cinematic-back'),orbit=root.querySelector('.memory-orbit');const atlas=new Image();atlas.src='./六幕场景图集.png';let act=0,t=0,raf,seen=new Set(),choice=0,dpr=1,w=1,h=1;
orbit.innerHTML=labels.map((x,i)=>`<button style="left:${[8,36,68,82,60,24,2,45][i]}%;top:${[12,2,16,47,72,68,44,38][i]}%" data-i="${i}">${x}</button>`).join('');
const lerp=(a,b,n)=>a+(b-a)*n,clamp=n=>Math.max(0,Math.min(1,n));
function resize(){dpr=Math.min(devicePixelRatio||1,1.7);w=innerWidth;h=innerHeight;canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
function mountain(y,amp,color,phase=0){ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(0,h);ctx.lineTo(0,y);for(let x=0;x<=w;x+=w/10)ctx.lineTo(x,y-Math.abs(Math.sin(x*.006+phase))*amp-Math.sin(x*.017+phase)*amp*.28);ctx.lineTo(w,h);ctx.closePath();ctx.fill()}
function flower(x,y,r,a=1){ctx.save();ctx.translate(x,y);ctx.strokeStyle=`rgba(239,228,193,${a})`;ctx.lineWidth=2;for(let i=0;i<8;i++){ctx.rotate(Math.PI/4);ctx.beginPath();ctx.ellipse(0,-r*.5,r*.18,r*.48,0,0,Math.PI*2);ctx.stroke()}ctx.restore()}
function bird(x,y,s,rot=0,color='#f2e7c9'){ctx.save();ctx.translate(x,y);ctx.rotate(rot);ctx.strokeStyle=color;ctx.lineWidth=Math.max(2,s*.045);ctx.beginPath();ctx.moveTo(-s,0);ctx.quadraticCurveTo(-s*.42,-s*.65,0,-s*.12);ctx.quadraticCurveTo(s*.42,-s*.65,s,0);ctx.stroke();ctx.restore()}
function crane(x,y,s,rot=0){ctx.save();ctx.translate(x,y);ctx.rotate(rot);ctx.fillStyle='#f2e7c9';ctx.strokeStyle='#102a40';ctx.lineWidth=Math.max(2,s*.018);ctx.beginPath();ctx.ellipse(0,0,s*.34,s*.13,-.08,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.beginPath();ctx.moveTo(-s*.08,-s*.03);ctx.bezierCurveTo(-s*.35,-s*.58,-s*.72,-s*.62,-s,-s*.28);ctx.bezierCurveTo(-s*.6,-s*.28,-s*.34,-s*.08,-s*.04,s*.04);ctx.closePath();ctx.moveTo(s*.05,-s*.02);ctx.bezierCurveTo(s*.32,-s*.56,s*.72,-s*.58,s,-s*.18);ctx.bezierCurveTo(s*.56,-s*.24,s*.3,-s*.06,s*.03,s*.05);ctx.closePath();ctx.fill();ctx.stroke();ctx.beginPath();ctx.moveTo(s*.27,-s*.03);ctx.bezierCurveTo(s*.48,-s*.2,s*.48,-s*.43,s*.7,-s*.47);ctx.stroke();ctx.fillStyle='#c45545';ctx.beginPath();ctx.arc(s*.72,-s*.48,s*.035,0,7);ctx.fill();ctx.restore()}
function clothPattern(alpha=1){ctx.strokeStyle=`rgba(236,224,188,${alpha})`;ctx.lineWidth=2;for(let y=90;y<h;y+=120){ctx.beginPath();ctx.moveTo(0,y);for(let x=0;x<w;x+=160)ctx.bezierCurveTo(x+45,y-36,x+110,y+36,x+160,y);ctx.stroke();for(let x=80;x<w;x+=240)flower(x,y,30,alpha)}}
function drawTable(p){ctx.fillStyle='#241710';ctx.fillRect(0,0,w,h);for(let i=0;i<18;i++){ctx.fillStyle=`rgba(122,76,45,${.07+i*.006})`;ctx.fillRect(0,i*h/18,w,h/40)}ctx.save();ctx.translate(w*.54,h*.46);ctx.rotate(-.035);ctx.fillStyle='#e8dfc8';ctx.fillRect(-w*.29,-h*.23,w*.58,h*.46);ctx.strokeStyle='#214d63';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(-w*.26,0);for(let x=-w*.26;x<w*.26;x+=24)ctx.lineTo(x,Math.sin(x*.034+t*1.4)*9);ctx.stroke();ctx.restore();ctx.fillStyle='#100c0a';ctx.beginPath();ctx.ellipse(w*.27,h*.78,120,200,-.6,0,Math.PI*2);ctx.ellipse(w*.82,h*.79,120,200,.6,0,Math.PI*2);ctx.fill();ctx.fillStyle='#d99a50';ctx.beginPath();ctx.arc(w*.88,h*.2,10+Math.sin(t*5)*2,0,7);ctx.fill()}
function drawMountains(p){ctx.fillStyle='#dfe9dd';ctx.fillRect(0,0,w,h);mountain(h*.67,170,'#9cbfc0',t*.08);mountain(h*.76,240,'#437f8b',1+t*.06);mountain(h*.88,290,'#143e59',2);ctx.strokeStyle='#e6dfc8';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(w*.48,h);ctx.bezierCurveTo(w*.36,h*.7,w*.66,h*.54,w*.55,h*.25);ctx.stroke();for(let i=0;i<45;i++){const x=(i*97)%w,y=h*.6+Math.sin(i*2.1)*h*.15;ctx.strokeStyle='#173e50';ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+Math.sin(t+i)*8,y-30-20*Math.sin(t*.8+i));ctx.stroke()}}
function drawMemory(){drawMountains(1);clothPattern(.18);labels.forEach((_,i)=>{const x=w*(.48+[.04,.15,.28,.36,.25,.1,-.03,.19][i]),y=h*(.15+[.06,.0,.1,.3,.48,.45,.27,.22][i]);flower(x,y,18+4*Math.sin(t+i),seen.has(i)?.95:.35)})}
function drawStorm(){const g=ctx.createLinearGradient(0,0,w,h);g.addColorStop(0,'#061d3d');g.addColorStop(.48,'#087eaa');g.addColorStop(1,'#7bbed0');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.save();ctx.translate(w*.55,h*.4);ctx.rotate(-.3);for(let i=0;i<120;i++){const z=(i*73+t*420)%Math.max(w,h),x=(i*137)%w-w*.5,y=(i*53)%h-h*.45;ctx.strokeStyle=`rgba(235,235,209,${.12+(i%5)*.08})`;ctx.lineWidth=1+i%3;ctx.beginPath();ctx.moveTo(x-z*.3,y-z*.12);ctx.lineTo(x+55-z*.3,y+22-z*.12);ctx.stroke()}ctx.restore();crane(w*.61,h*.39,Math.min(w,h)*.25,-.12);for(let i=0;i<12;i++)bird((i*151+t*28)%w,(i*83)%h*.66,26+i%4*9,-.1,'#081b31');for(let i=0;i<34;i++){ctx.save();ctx.translate((i*173+t*90*(1+i%3))%w,(i*97+t*45)%h);ctx.rotate(t+i);ctx.fillStyle=i%3?'#e9dfc5':'#174e74';ctx.fillRect(-18,-4,36,8);ctx.restore()}}
function drawChoice(){drawTable(1);ctx.save();ctx.translate(w*.58,h*.43);ctx.rotate(-.035);ctx.beginPath();ctx.rect(-w*.27,-h*.2,w*.54,h*.4);ctx.clip();ctx.fillStyle='#0b4567';ctx.fillRect(-w*.3,-h*.3,w*.6,h*.6);clothPattern(.72);for(let i=0;i<7;i++)flower(-w*.2+i*w*.07,Math.sin(i+choice)*48,28+choice*3,.95);ctx.restore()}
function drawReturn(){const g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,'#9bd0cf');g.addColorStop(.5,'#226f82');g.addColorStop(1,'#082b43');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);mountain(h*.72,160,'#10465c',t*.05);mountain(h*.87,210,'#06283f',1);clothPattern(.42);ctx.save();ctx.translate(w*.7,h*.55);ctx.fillStyle='#071824';ctx.beginPath();ctx.arc(0,-h*.28,48,0,7);ctx.moveTo(-48,-h*.22);ctx.quadraticCurveTo(-130,h*.05,-105,h*.42);ctx.lineTo(105,h*.42);ctx.quadraticCurveTo(130,h*.05,48,-h*.22);ctx.closePath();ctx.fill();ctx.clip();ctx.strokeStyle='#e9dfbc';clothPattern(.9);ctx.restore();crane(w*.82,h*.16,72,-.08);ctx.globalAlpha=.28;ctx.fillStyle='#e9dfc8';ctx.beginPath();ctx.arc(w*.24,h*.62,18,0,7);ctx.moveTo(w*.222,h*.65);ctx.quadraticCurveTo(w*.2,h*.73,w*.214,h*.86);ctx.lineTo(w*.266,h*.86);ctx.quadraticCurveTo(w*.28,h*.73,w*.258,h*.65);ctx.closePath();ctx.fill();ctx.globalAlpha=1}
function drawAtlas(i){const sw=atlas.naturalWidth/3,sh=atlas.naturalHeight/2,sx=i%3*sw,sy=Math.floor(i/3)*sh;const zoom=1.035+Math.sin(t*.22)*.006,scale=Math.max(w/sw,h/sh)*zoom,dw=sw*scale,dh=sh*scale;ctx.drawImage(atlas,sx,sy,sw,sh,(w-dw)/2,(h-dh)/2,dw,dh);const shade=ctx.createLinearGradient(0,0,w*.72,0);shade.addColorStop(0,'rgba(3,16,27,.7)');shade.addColorStop(.52,'rgba(3,16,27,.13)');shade.addColorStop(1,'rgba(3,16,27,.02)');ctx.fillStyle=shade;ctx.fillRect(0,0,w,h);if(i===3){ctx.save();ctx.globalAlpha=.38;ctx.strokeStyle='#e8dfc8';for(let k=0;k<38;k++){const y=(k*79+t*130)%h,x=(k*137+t*240)%w;ctx.lineWidth=1+k%3;ctx.beginPath();ctx.moveTo(x-90,y-50);ctx.lineTo(x+28,y+18);ctx.stroke()}ctx.restore()}if(i===5){ctx.save();ctx.globalCompositeOperation='screen';ctx.globalAlpha=.13+.05*Math.sin(t);clothPattern(.7);ctx.restore()}}
function frame(now){t=now/1000;ctx.clearRect(0,0,w,h);if(atlas.complete&&atlas.naturalWidth)drawAtlas(act);else if(act===0)drawTable();else if(act===1)drawMountains();else if(act===2)drawMemory();else if(act===3)drawStorm();else if(act===4)drawChoice();else drawReturn();raf=requestAnimationFrame(frame)}
function render(){root.dataset.act=act;const s=scenes[act];count.textContent=`第 ${act+1} 幕 / 6 · ${s[0]}`;title.textContent=s[1];copy.textContent=s[2];back.hidden=act===0;next.textContent=act===5?'重新走一遍':'进入下一幕';orbit.style.display=act===2?'block':'none';root.classList.remove('is-changing');void root.offsetWidth;root.classList.add('is-changing');dispatchEvent(new CustomEvent('story-scene',{detail:act}))}
function open(){root.classList.add('is-open');act=0;render();cancelAnimationFrame(raf);raf=requestAnimationFrame(frame)}function close(){root.classList.remove('is-open');cancelAnimationFrame(raf)}
next.onclick=()=>{act=act===5?0:act+1;render()};back.onclick=()=>{act=Math.max(0,act-1);render()};root.querySelector('.cinematic-close').onclick=close;orbit.querySelectorAll('button').forEach(b=>b.onclick=()=>{seen.add(+b.dataset.i);b.dataset.seen='true';dispatchEvent(new CustomEvent('observe-memory',{detail:['flower','vine','stream','fish','butterfly','tree','village','bird'][+b.dataset.i]}))});root.querySelectorAll('.choice-strip button').forEach((b,i)=>b.onclick=()=>{choice=i;root.querySelectorAll('.choice-strip button').forEach((x,j)=>x.setAttribute('aria-pressed',String(i===j))) });document.getElementById('begin')?.addEventListener('click',open);addEventListener('open-cinematic',open);
const launch=document.createElement('button');launch.className='act-toggle cinematic-launch';launch.textContent='进入六幕正片';launch.onclick=open;document.body.append(launch);
