import {storyCopy} from './story-copy.js?v=64';
export const dictionary={
'布上的曲线，原来是刚才那道溪水。外婆把山野，留在了这里。':'The curve on the cloth echoes the stream you just saw. Grandma kept the wilds here.',
'布上的花，原来也有山野里舒展的模样。你开始懂得外婆的笔。':'The flowers on the cloth unfold like those in the valley. You begin to understand Grandma’s drawing.',
'晾晒布上的花、水和鸟，与山野彼此呼应。原来外婆画下的，是她认真看过的生活。':'Flowers, water and birds on the drying cloth echo the valley. Grandma drew the life she had taken time to see.',
'古树 · 点击触摸记忆':'Old tree · Touch a memory','花朵 · 点击观察':'Flowers · Click to observe','溪水 · 点击听故事':'Stream · Click for its story','游鱼 · 点击观察':'Fish · Click to observe','蝴蝶 · 点击观察':'Butterfly · Click to observe','鸟 · 点击听故事':'Bird · Click for its story',
'山野 · 苏醒':'The wilds · Awakening','轻触花朵，让山野回应你':'Touch a flower and let the wilds answer','山野，在你指尖苏醒。':'The wilds awaken at your fingertips.','外婆说，先别急着画。等一阵风，等一朵花，让山里的生命先认出你。':'Grandma said: do not rush to draw. Wait for the wind, wait for a flower. Let the life of the hills get to know you.','唤醒这一片花海':'Awaken the flowers','拖动体验进度':'Drag to move through the experience','入山':'Into the wilds','拾纹':'Gathering patterns','归途':'The way home','成布':'Finished cloth','在山野中停下来观察':'Pause and observe the wilds',
'山野入蓝':'Into the Indigo Wilds','一场蜡染归乡':'A batik journey home','蓝里，有人等你':'Lanli, someone is waiting for you','蓝里，有人等你。':'Lanli, someone is waiting for you.',
'外婆留下一块已画好蜡花、尚未染色的白布。手记最后一页写着：“蓝里，最后一笔，不在纸上。”你决定先去看看她笔下的山野，再回来完成这块布。':'Grandma left a white cloth, its wax patterns drawn but not yet dyed. On the last page of her journal: “Lanli, the final stroke is not on paper.” You set out to see the wilds she drew, before returning to finish the cloth.',
'翻开手记，走进山野 →':'Open the journal · Enter the wilds →','暂停':'Pause','继续':'Continue','全屏':'Full screen','暂停动画':'Pause animation','全屏观看':'View full screen','重新开始':'Start again','声音：开启':'Sound: On','声音：关闭':'Sound: Off','开启环境声音':'Turn ambient sound on','关闭环境声音':'Turn ambient sound off','请在浏览器打开全屏':'Use your browser’s full-screen mode','画面加载失败，请刷新页面重试。':'The scene could not load. Please refresh and try again.',
'远处的染亭，正在晾晒山野。':'The wilds hang out to dry at the distant pavilion.','两个人在亭中点蜡，蓝布随风轻轻起伏。移动鼠标观看山谷，收集六段山野记忆，再轻触亭中的蓝布，让鸟群带你继续。':'Two people apply wax in the pavilion as indigo cloth stirs in the breeze. Move your mouse to explore the valley. Gather six memories, then touch the blue cloth to follow the birds onward.','轻触蓝布，继续旅程 →':'Touch the blue cloth · Continue →','山野 · 染亭':'The valley · Dyeing pavilion','晾晒的蓝布 · 集齐手记后放飞':'Drying cloth · Gather all memories to release the birds','鸟从布上醒来，飞向山野。':'Birds awaken on the cloth and take to the sky.','一只鸟带起另一只鸟，蜡染里的花与水也跟着舒展。抬头，跟随它们的方向。':'One bird lifts another into flight. Flowers and water unfold with them. Look up and follow their path.','鸟群正在飞向蓝布…':'The flock is flying toward the indigo cloth…',
'山野手记':'Valley journal','手记':'Journal','山野记忆收集进度':'Memories collected','继续探索山野':'Keep exploring','已集齐 · 点击蓝布继续':'All found · Touch the blue cloth','古树的树皮':'The old tree’s bark','花开的地方':'Where flowers open','溪水的方向':'The stream’s direction','水里的鱼':'Fish beneath the water','蝴蝶的消息':'A butterfly’s message','鸟与归途':'Birds and the way home','树还记得，那只小小的手。':'The tree remembers that small hand.','这朵花，外婆已经等过许多个春天。':'Grandma waited many springs for this flower.','水绕过石头，仍然知道往哪里去。':'Water bends around stones, still knowing its way.','你不动了，鱼才重新来到光里。':'When you grow still, the fish return to the light.','她讲过的故事，今天落在你的袖口。':'A story she once told settles on your sleeve.','它起飞的时候，你终于抬起了头。':'As it takes flight, you finally look up.',
'合上 ×':'Close ×','合上手记':'Close journal','故事插画':'Story illustration','上一页':'Previous','继续读故事 →':'Read on →','把这一刻收进手记':'Keep this moment','记忆已在手记里':'Memory already saved','带回家的记忆':'Memories to bring home','花留在枝头，鱼仍在水里。你把这些时刻，带进了外婆留下的空白。':'Flowers stay on their branches; fish remain in the water. You carry these moments into the space Grandma left for you.','手记还空着。先在山野里停一停，读完一个故事，再把它收进来。':'The journal is still empty. Pause in the valley, read a story to the end, and keep its memory.','已收进手记':'Saved in your journal','待寻找':'Still to find','左侧山脚的古树':'The old tree at the foot of the left mountain','两侧山脚的花朵':'Flowers along the mountain slopes','中央流动的溪水':'The flowing stream in the middle','溪水中的游鱼':'Fish swimming in the stream','右侧低飞的蝴蝶':'Butterflies flying low on the right','偏左中部飞翔的鸟':'The bird flying just left of centre','合上手记，继续探索':'Close journal · Keep exploring','已记住':'Remembered','观察':'Observe','点击观察':'Click to observe','回工坊，完成白布':'Return to the workshop · Finish the cloth',
'外婆留下的蜡还在布上。让这块已画蜡的白布，慢慢入蓝。':'Grandma’s wax is still on the cloth. Let this patterned white cloth slowly enter the indigo.','将白布浸入染液':'Lower the cloth into the dye','布已浸染。把它提出染液，让空气唤出蓝色。':'The cloth is dyed. Lift it out and let the air bring out its blue.','出缸，等待氧化':'Lift out · Let it oxidise','蜡仍保护着花鸟的白。将染好的布放入热水脱蜡。':'Wax still protects the white flowers and birds. Place the dyed cloth in hot water to remove the wax.','热水煮布，融去蜡':'Heat in water · Melt away the wax','融化的蜡离开布面。清洗、晾晒，让白色纹样显露。':'The melted wax leaves the cloth. Rinse and hang it to dry, revealing the white patterns.','清洗晾晒，展开全幅':'Rinse, dry and unfold','外婆没有教我画一朵花。她教我，怎样等一朵花自己开口。':'Grandma did not teach me to draw a flower. She taught me to wait until a flower could speak for itself.','放大细看':'Take a closer look','查看全幅':'View the whole cloth','回到亭子 ×':'Return to the pavilion ×','自动演示':'Auto demonstration','请稍候…':'Please wait…','工艺交互示意：浸染、氧化与热水脱蜡的时间已压缩；画面不代表实际操作时长。':'Interactive process illustration: dyeing, oxidation and hot-water wax removal are shortened here, not shown in real time.',
'按住布面，向下拖动，让白布入染':'Hold the cloth and drag down to immerse it','按住布面，向上提起，观察空气带出的蓝':'Hold and drag up; watch the blue emerge in the air','轻触布面，放入热水；等待热量融去蜡':'Touch the cloth to place it in hot water; let the wax melt','清洗后的布，向一侧拖开，展开全幅':'Drag the rinsed cloth sideways to unfold it','向下浸入染液':'Lower into the dye','向上提出，蓝色渐显':'Lift out; blue begins to emerge','向两侧展开白纹':'Unfold the white patterns','布面未能载入，请返回亭子后重试。':'The cloth could not load. Return to the pavilion and try again.','染液浸入纤维，蜡覆盖的地方保留着白。':'Dye enters the fibres; wax-covered areas remain white.','提出布面，接触空气，蓝色渐渐变深。':'Lift the cloth into the air; the blue gradually deepens.','热水使蜡融化，蜡离开纤维，白色花鸟显露。':'Hot water melts the wax out of the fibres, revealing white flowers and birds.','洗去残蜡与浮色，晾干，展开山野。':'Rinse away remaining wax and loose dye, dry, and unfold the wilds.',
'继续这段归途':'Continue the journey home','重看这块布':'See the cloth again','翻阅手记':'Read the journal','重新出发':'Begin a new journey','归来':'Homecoming','山野，留在了布上。':'The wilds remain on the cloth.','让这块布在风里，慢慢晾干。':'Let the cloth dry slowly in the breeze.','你又回到了外婆的木桌。':'You return to Grandma’s wooden table.','出发前留在这里的白布，如今已经入蓝。':'The white cloth you left behind has now turned indigo.','“最后一笔，不在纸上。”':'“The final stroke is not on paper.”','原来，空白是在等你。':'The empty space was waiting for you.','我终于明白，外婆留下的空白，是让我把自己的故事带回来。':'At last I understand: Grandma left that space so I could bring back a story of my own.','山野留在布上，你的故事还会继续。':'The wilds stay on the cloth. Your story continues.','你从外婆的木桌出发，把这块白布带回了蓝里。':'From Grandma’s table you set out, and brought this white cloth home to indigo.',
'你翻阅了花开的记忆。':'You revisited the memory of a flower opening. ','你读到了溪边洗布的往事。':'You remembered washing cloth by the stream. ','你读过等待游鱼的片刻。':'You remembered waiting for the fish. ','你翻阅了鸟与归途的故事。':'You followed the birds’ story home. ','你读过蝴蝶停留的片刻。':'You remembered a butterfly’s brief pause. ','你读过外婆与老树的往事。':'You revisited Grandma and the old tree. ',
'外婆的木桌、白布与蜡染工具':'Grandma’s wooden table, white cloth and batik tools','蓝白花鸟蜡染手记':'Indigo-and-white journal with flower and bird patterns','露水中的半开野花与花苞':'Dew-covered wildflowers and buds','外婆与孩子在绕石流动的溪水边触水':'Grandma and a child touching the stream beside stones','岩石旁的浅水里游着几尾小鱼':'Small fish swimming in shallow water beside rocks','蝴蝶停在叶上，双翅半开':'A butterfly rests on a leaf, wings half open','外婆与孩子把手放在古树的树皮上':'Grandma and a child touching the old tree’s bark','窗边的小鸟与桌上花鸟纹蓝布':'A bird by the window and patterned indigo cloth on the table','完成的蓝白蜡染自然铺在外婆的木桌上':'Finished indigo-and-white batik laid on Grandma’s table','上蜡白布的浸染与热水脱蜡过程':'Dyeing wax-patterned cloth and removing wax in hot water','老师指定的蓝白蜡染图':'Indigo-and-white batik artwork'
};
const stories={
flower:['The roadside flower was half closed, water clinging to its leaves. Grandma stopped and watched. I urged her on. “How could I start drawing before I have really seen it?” she asked.','We waited as the petals opened. Wind stirred the slender stem, then carried light into the flower’s heart. Grandma did not pick it. Following the leaves, she drew the first curve in her journal.','Back at the table, I understand her pause. A flower is not simply a pattern to copy, but a lesson in patient looking. Its wax shape is already on the cloth, waiting for me to finish the colour.'],
stream:['The stream curved around stones and spread into the shallows. When I was little, Grandma guided my hand into it to feel the water before gently lowering the cloth.','The water did not run straight. It turned at each stone, then flowed onward. “Remember that bend,” Grandma said. “Do not make it too neat.”','I leave a curved line in the journal. It is not an answer—only water I touched with my own hand, and the patience Grandma taught me that day.'],
fish:['As my shadow fell on the water, the fish scattered. Grandma asked me to sit still and not reach after them.','After a long wait, the water grew quiet again. One fish peered out from behind a stone, then another and another. They darted left and right, always within the clear water.','I keep that waiting with me. A cloth can hold fish from the water and birds from the sky. First let life move freely; only then decide where to begin drawing.'],
butterfly:['A butterfly rested on a leaf. Grandma did not chase it. She asked me to watch its wings close and slowly open, like a page turning in the wind.','Holding my breath, I noticed that each opening was a little different. Sunlight lingered on the texture of its wings, then left with it as it took flight.','When the butterfly left, the leaf remained. I remembered Grandma turning the journal’s pages. A story may pass out of sight, but a shape we have truly seen can stay with us.'],
tree:['Grandma held little Lanli’s hand and stopped beside the old tree. Its roots spread across the ground; even two people could not reach around its trunk. Light fell through its crooked branches.','“Touch gently. Do not peel it.” Grandma placed my hand on the trunk. My palm felt the ridges, my fingertips followed the cracks. A small patch of moss clung to the shaded side.','Years later, I place my hand on the trunk again. I cannot see the rings inside, but I remember the rough bark—and the hand that once rested over mine.'],
bird:['When Grandma drew birds, she moved the cloth closer to the window. “More light here. Easier to see.” A bird called outside, as though answering her.','I looked up as a bird swept past the eaves, folding its wings before opening them to the wind. Branches, water and sky seemed, for a moment, to share a direction.','Back beside the pavilion, I touch the drying indigo cloth. Birds rise from its surface, carrying the flowers, water and light I remember, higher into the valley sky.']
};
for(const key of Object.keys(stories)) storyCopy[key].forEach((zh,i)=>dictionary[zh]=stories[key][i]);
