import {addLandmarks} from './encounter-landmarks.js?v=60';
import * as T from './three.module.js';
import {createFlightTransition} from './flight-transition.js?v=43';
import {aimPavilionCamera} from './pavilion-flight-path.js?v=2';
import {createPavilion} from './pavilion.js?v=74';
import {paintScene} from './painted.js?v=1';
import {clothTexture,reopenLetter} from './story.js?v=22';
import './journey.js?v=73';
import './story-thread.js?v=72';
import './sound.js?v=50';
import {createBird,createFish,createButterfly,curvedPetal} from './fauna.js';
import {resetJourney} from './journey-state.js';
const el=id=>document.getElementById(id),clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x)),smooth=x=>{x=clamp(x);return x*x*(3-2*x)},mix=T.MathUtils.lerp;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const scene=new T.Scene();scene.background=new T.Color('#f3e6cf');scene.fog=new T.Fog('#dce9cf',24,90);
const camera=new T.PerspectiveCamera(43,1,.1,160);const renderer=new T.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.outputColorSpace=T.SRGBColorSpace;el('world').append(renderer.domElement);
const impact=document.createElement('div');impact.id='impact-title';impact.innerHTML='<span></span>';el('world').append(impact);const impactStyle=document.createElement('style');impactStyle.textContent='#impact-title{position:absolute;inset:0;display:grid;place-items:center;pointer-events:none;opacity:0;z-index:4;background:radial-gradient(circle,#0c759955,#071e31dd);mix-blend-mode:multiply;transition:opacity .25s}#impact-title span{font:clamp(38px,9vw,120px) serif;letter-spacing:.22em;color:#f5ecd5;text-shadow:0 3px 28px #001c;transform:translateY(14px);transition:transform .5s}.impact-on{opacity:1!important}.impact-on span{transform:translateY(0)!important}';document.head.append(impactStyle);
scene.add(new T.HemisphereLight('#fff7e3','#5c8e9b',1.6));const sunlight=new T.DirectionalLight('#fff0e0',1.4);sunlight.position.set(-12,24,8);scene.add(sunlight);renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;
const earth=new T.Group();scene.add(earth);const sky=new T.Group();scene.add(sky);
renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFShadowMap;sunlight.castShadow=true;sunlight.shadow.mapSize.set(2048,2048);Object.assign(sunlight.shadow.camera,{left:-18,right:18,top:24,bottom:-15,near:.5,far:85});sunlight.shadow.bias=-.0003;sunlight.shadow.normalBias=.04;sunlight.shadow.radius=3;
let seed=2041;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};
const material=(color)=>{const m=new T.MeshStandardMaterial({color,roughness:1,flatShading:true,side:T.DoubleSide});m.onBeforeCompile=s=>{s.vertexShader='varying vec3 clothPoint;\n'+s.vertexShader;s.vertexShader=s.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\nclothPoint = position;');s.fragmentShader='varying vec3 clothPoint;\n'+s.fragmentShader;s.fragmentShader=s.fragmentShader.replace('#include <color_fragment>',`#include <color_fragment>
float warp=sin(clothPoint.x*190.0)*sin(clothPoint.y*210.0+clothPoint.z*170.0);
float fleck=fract(sin(dot(floor(clothPoint.xy*180.0),vec2(12.98,78.23)))*43758.54);
diffuseColor.rgb*=0.9+warp*0.06+fleck*0.16;`)};return m};
const greens=['#123451','#265171','#436888','#8099ab'],corals=['#2d5371','#587b94','#adbbc3'],leaves=greens.map(material),petalMats=['#f0e8d1','#c8d6d7','#e8e4d3'].map(material),ink=material('#112d47'),cream=material('#f4ebd4');
function mesh(g,m,parent,x=0,y=0,z=0){const o=new T.Mesh(g,m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o}
// 第一幕：外婆的木桌。先用明确的桌面、桌边和工具建立故事地点，再让纹样带入山野。
const tableScene=new T.Group();scene.add(tableScene);
const woodMat=new T.MeshStandardMaterial({color:'#6f432b',roughness:.92});
const woodEdgeMat=new T.MeshStandardMaterial({color:'#3b251b',roughness:1});
mesh(new T.BoxGeometry(18,.65,13),woodMat,tableScene,0,0,-1);
mesh(new T.BoxGeometry(18,.16,.18),woodEdgeMat,tableScene,0,.34,5.42);mesh(new T.BoxGeometry(18,.16,.18),woodEdgeMat,tableScene,0,.34,-7.42);
const tableCloth=mesh(new T.PlaneGeometry(8.2,5.6,24,18),new T.MeshStandardMaterial({color:'#f3ead6',roughness:1,side:T.DoubleSide}),tableScene,-1.2,.38,-.8);tableCloth.rotation.x=-Math.PI/2;
const clothLine=new T.Line(new T.BufferGeometry().setFromPoints([new T.Vector3(-4.5,.42,-1.8),new T.Vector3(-2.3,.42,-.9),new T.Vector3(-.7,.42,-1.4),new T.Vector3(.8,.42,-.2),new T.Vector3(2.7,.42,-.8),new T.Vector3(3.4,.42,.7)]),new T.LineBasicMaterial({color:'#1f6380',transparent:true,opacity:.8}));tableScene.add(clothLine);
mesh(new T.CylinderGeometry(1.25,1.05,.45,32),new T.MeshStandardMaterial({color:'#254f65',roughness:.8}),tableScene,4.4,.7,2.9);mesh(new T.CylinderGeometry(.92,.92,.04,32),new T.MeshBasicMaterial({color:'#0e2638'}),tableScene,4.4,.94,2.9);
const wax=mesh(new T.CylinderGeometry(.32,.42,.7,18),new T.MeshStandardMaterial({color:'#d4b56f',roughness:1}),tableScene,3.1,.85,2.3);wax.rotation.z=-.25;
const stylus=mesh(new T.CylinderGeometry(.09,.13,3.2,10),new T.MeshStandardMaterial({color:'#c3a26d',roughness:.8}),tableScene,2.3,1.05,1.25);stylus.rotation.z=-.75;
const notebook=mesh(new T.BoxGeometry(3.2,.12,2.3),new T.MeshStandardMaterial({color:'#d8c7a8',roughness:1}),tableScene,-5.2,.58,2.8);notebook.rotation.y=-.12;
// 抬到地形平面之上，避免被山野的地面遮住。
tableScene.position.set(0,.9,-1);tableScene.rotation.x=-.06;
// Sculpted relief: separate ridges with real depth, not a projected panorama.
const ground=mesh(new T.PlaneGeometry(130,130,30,30),material('#b9c6cd'),earth,0,-.25,-30);ground.rotation.x=-Math.PI/2;
for(let i=0;i<42;i++){const side=i%2?1:-1,z=-i*1.9-2,x=side*(10+rand()*12);const h=4+rand()*10;const profile=[];const radius=2.4+rand()*2;for(let j=0;j<=10;j++){const y=j/10;profile.push(new T.Vector2(radius*(.18+.82*Math.pow(1-y,.55))*(1+.1*Math.sin(j*1.9)),y*h))}profile.push(new T.Vector2(0,h+.12));const g=new T.LatheGeometry(profile,7);const o=mesh(g,material(i%3?greens[i%4]:corals[i%3]),earth,x,-.2,z);o.rotation.y=rand()*3;o.scale.z=.65;const edges=new T.LineSegments(new T.EdgesGeometry(g,20),new T.LineBasicMaterial({color:'#244d58',transparent:true,opacity:.24}));o.add(edges)}
// A ribbon of water meanders between the mountains.
const riverPoints=[];for(let i=0;i<65;i++){const z=13-i*1.1;riverPoints.push(new T.Vector3(Math.sin(i*.13)*2.3,.02,z))}const riverPath=new T.CatmullRomCurve3(riverPoints);const riverGeo=new T.BufferGeometry(),rv=[],ri=[];for(let i=0;i<=160;i++){const u=i/160,p=riverPath.getPoint(u),tan=riverPath.getTangent(u),n=new T.Vector3(-tan.z,0,tan.x),width=1.5+.45*Math.sin(u*15);rv.push(p.x+n.x*width,.36,p.z+n.z*width,p.x-n.x*width,.36,p.z-n.z*width);if(i<160){let a=i*2;ri.push(a,a+1,a+2,a+1,a+3,a+2)}}riverGeo.setAttribute('position',new T.Float32BufferAttribute(rv,3));riverGeo.setIndex(ri);riverGeo.computeVertexNormals();const riverUV=[];for(let i=0;i<=160;i++)riverUV.push(0,i/160,1,i/160);riverGeo.setAttribute('uv',new T.Float32BufferAttribute(riverUV,2));
const waterMaterial=new T.ShaderMaterial({transparent:true,depthWrite:false,side:T.DoubleSide,uniforms:{time:{value:0}},vertexShader:'varying vec2 waterUV; void main(){waterUV=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',fragmentShader:`varying vec2 waterUV;uniform float time;void main(){float across=waterUV.x;float flow=waterUV.y*145.0+time*1.9;float wave=sin(flow+sin(across*15.0+time*.7)*.65);float glint=pow(max(0.0,wave),20.0);float edge=smoothstep(.39,.50,abs(across-.5));vec3 blue=mix(vec3(.12,.39,.47),vec3(.42,.68,.69),abs(across-.5)*2.0);blue=mix(blue,vec3(.85,.94,.87),glint*.58+edge*.25);gl_FragColor=vec4(blue,.42+glint*.17+edge*.12);}`});
const riverSurface=mesh(riverGeo,waterMaterial,earth);riverSurface.castShadow=false;
const bed=mesh(riverGeo.clone(),new T.MeshBasicMaterial({color:'#577b80',side:T.DoubleSide}),earth);bed.position.y=-.54;bed.castShadow=false;
for(let i=0;i<45;i++){const u=i/55,point=riverPath.getPoint(u),tangent=riverPath.getTangent(u),width=1.5+.45*Math.sin(u*15);for(const side of [-1,1]){const stone=mesh(new T.SphereGeometry(.16+rand()*.16,7,5),material('#a6b5ac'),earth,point.x-tangent.z*(width+.12)*side,-.10,point.z+tangent.x*(width+.12)*side);stone.scale.set(1.3,.42,1);stone.castShadow=false;}}

const ripples=[];for(let i=0;i<120;i++){const u=rand(),p=riverPath.getPoint(u);const geom=new T.PlaneGeometry(.15+rand()*.45,.016);const o=mesh(geom,new T.MeshBasicMaterial({color:'#d6eeee',transparent:true,opacity:.45,depthWrite:false,side:T.DoubleSide}),earth,p.x+(rand()-.5)*2,.06,p.z);o.rotation.x=-Math.PI/2;o.userData.flow={u,offset:(rand()-.5)*1.6};o.castShadow=false;ripples.push(o)}
// Leaves and petals are individually hinged paper volumes.
function leafGeo(length,width){const s=new T.Shape();s.moveTo(0,0);s.bezierCurveTo(width*.7,length*.18,width*.6,length*.66,0,length);s.bezierCurveTo(-width*.6,length*.66,-width*.7,length*.18,0,0);return new T.ShapeGeometry(s,12)}
const leafShape=curvedPetal(1,.62),petalShape=curvedPetal(1,.84);
const plants=[];const pickTargets=[];
const updateLandmarks=addLandmarks(earth,pickTargets);
const streamHit=mesh(riverGeo.clone(),new T.MeshBasicMaterial({visible:false,side:T.DoubleSide}),earth);streamHit.scale.x=1.08;streamHit.userData.memory='stream';pickTargets.push(streamHit);
function plant(x,z,index){const root=new T.Group();root.position.set(x,0,z);earth.add(root);const height=(.9+rand()*.55)*(.65+.35*clamp((z+26)/32));const stemCurve=new T.CatmullRomCurve3([new T.Vector3(0,0,0),new T.Vector3(.12,height*.4,0),new T.Vector3(-.13,height*.8,.04),new T.Vector3(0,height,0)]);mesh(new T.TubeGeometry(stemCurve,12,.035,5,false),leaves[0],root);const leafGroups=[];for(let k=0;k<5;k++){const hinge=new T.Group();hinge.position.set(0,height*(.17+k*.13),0);root.add(hinge);const l=mesh(leafShape,leaves[(k+index)%4],hinge);l.scale.setScalar(.8+(k%2)*.2);hinge.rotation.z=(k%2?1:-1)*1.06;hinge.rotation.y=k*1.9;leafGroups.push(hinge);const vein=mesh(new T.CylinderGeometry(.009,.013,.83,3),cream,l,0,.46,.009);vein.material=leaves[0]}
const bloom=new T.Group();bloom.position.y=height;root.add(bloom);const petals=[];for(let j=0;j<10;j++){const pivot=new T.Group();pivot.rotation.y=j*Math.PI*.2;bloom.add(pivot);const p=mesh(petalShape,petalMats[index%3],pivot);p.scale.set(.73,.85,.73);petals.push(pivot)}mesh(new T.SphereGeometry(.18,9,6),material('#d7ac48'),bloom,0,.1,0);const hit=mesh(new T.SphereGeometry(.85,6,4),new T.MeshBasicMaterial({visible:false}),bloom);hit.userData.plant=index;pickTargets.push(hit);plants.push({root,bloom,petals,leafGroups,index,height,offset:rand()*.18})}
for(let i=0;i<34;i++){let side=i%2?1:-1;plant(side*(5.4+rand()*3.2),6-rand()*32,i)}
// Foreground leaves frame the route; their occlusion changes as the camera advances.
// Oversized foreground leaf blockers removed.
// Articulated birds: body, tail, two wing joints and separate layered feathers.
const birds=[];for(let i=0;i<12;i++){const o=createBird(i===0?1.6:.7,i===0);sky.add(o.b);pickTargets.push(o.b);birds.push({...o,offset:rand()*6,base:new T.Vector3((rand()-.5)*24,(rand()-.5)*12,-rand()*24)})}
const perched=createBird(.78,true);perched.b.position.set(-2.6,3.45,2.8);perched.b.rotation.y=-.65;earth.add(perched.b);const birdHit=mesh(new T.SphereGeometry(.85,8,6),new T.MeshBasicMaterial({visible:false}),perched.b);birdHit.userData.memory='bird';pickTargets.push(perched.b);
const fishSchool=[];for(let i=0;i<5;i++){const o=createFish();earth.add(o);o.position.set(.3+i*.24,.19,5-i*1.4);o.scale.set(.72,.45,.72);o.traverse(part=>{part.castShadow=false;part.receiveShadow=false;});const fishTouch=new T.Mesh(new T.SphereGeometry(.85,10,8),new T.MeshBasicMaterial({visible:false}));fishTouch.scale.set(1,1.8,1);fishTouch.userData.memory='fish';o.add(fishTouch);pickTargets.push(o);fishSchool.push(o)}
const butterflies=[];for(let i=0;i<3;i++){const o=createButterfly();earth.add(o.b);pickTargets.push(o.b);butterflies.push(o)}
// Long directional glints establish the flight vector.
const glintPositions=new Float32Array(280*6);for(let i=0;i<280;i++){const x=(rand()-.5)*65,y=(rand()-.5)*45,z=-rand()*70;glintPositions.set([x,y,z,x+.22,y+.6,z-.6],i*6)}const glintGeo=new T.BufferGeometry();glintGeo.setAttribute('position',new T.BufferAttribute(glintPositions,3));const glintMat=new T.LineBasicMaterial({color:'#e3ddba',transparent:true,opacity:0});const glints=new T.LineSegments(glintGeo,glintMat);sky.add(glints);
const storm=new T.Group();storm.visible=false;sky.add(storm);const stormMats=['#06253f','#0c5072','#177c93','#b8d9d4'].map(c=>new T.MeshBasicMaterial({color:c,transparent:true,opacity:.65,side:T.DoubleSide,depthWrite:false}));const stormPieces=[];
for(let i=0;i<80;i++){const g=new T.PlaneGeometry(.5+rand()*2.8,.08+rand()*.24);const o=new T.Mesh(g,stormMats[i%4]);o.position.set((rand()-.5)*34,(rand()-.5)*22,-8-rand()*38);o.rotation.set(rand()*2,rand()*2,rand()*6);storm.add(o);stormPieces.push({o,base:o.position.clone(),speed:.7+rand()*1.8})}
const giantBird=new T.Group();storm.add(giantBird);const birdLine=new T.LineBasicMaterial({color:'#f3ead4',transparent:true,opacity:0});const wing=side=>new T.Line(new T.BufferGeometry().setFromPoints([new T.Vector3(0,0,0),new T.Vector3(side*3,1.4,0),new T.Vector3(side*7,.2,-.4),new T.Vector3(side*4,-1.1,0),new T.Vector3(side*1,-.35,0)]),birdLine);giantBird.add(wing(-1),wing(1));giantBird.position.set(0,5,-12);giantBird.scale.setScalar(2.4);
const sun=mesh(new T.SphereGeometry(3.8,36,24),new T.MeshBasicMaterial({color:'#f1c49b'}),earth,-12,18,-49);
sun.material.color.set('#eee6d2');
const textileMap=clothTexture(T),textileGeo=new T.PlaneGeometry(8,9,60,60),textileMat=new T.MeshBasicMaterial({map:textileMap,side:T.DoubleSide,transparent:true,opacity:0});const textile=mesh(textileGeo,textileMat,scene,0,6,1);const textileBase=Float32Array.from(textileGeo.attributes.position.array);
let birdEntryStart=0;let progress=0,target=0,playing=true,autoFlight=false,elapsed=0,burst=0,shock=0,lastStage=-1,hover=-1;const pointer=new T.Vector2(),raycaster=new T.Raycaster();let mx=0,my=0;const timeStart=performance.now();let last=performance.now();
let panelWasPlaying=true;addEventListener('story-panel',e=>{if(e.detail){panelWasPlaying=playing;playing=false}else playing=panelWasPlaying});
addEventListener('observe-memory',e=>{const memory=e.detail;shock=memory==='bird'?.35:memory==='tree'?.3:.15;if(memory==='flower')burst=1;});
let clothCompleted=false;
addEventListener('story-scene',e=>{const act=Number(e.detail);target=[0,.08,.36,.72,.95,1][act]??0;autoFlight=false;lastStage=-1;shock=act===3?1:act===2?.7:act===4?.35:0;if(act===2)burst=1;impact.querySelector('span').textContent=['空白','入山','相遇','风起','回桌','归途'][act]??'';impact.classList.remove('impact-on');void impact.offsetWidth;impact.classList.add('impact-on');setTimeout(()=>impact.classList.remove('impact-on'),900);});
addEventListener('story-restart',()=>{clothCompleted=false;target=progress=0;autoFlight=false;lastStage=-1;});
addEventListener('cloth-finished',e=>{textileMat.map?.dispose();const snapshot=document.createElement('canvas');snapshot.width=e.detail.width;snapshot.height=e.detail.height;snapshot.getContext('2d').drawImage(e.detail,0,0);textileMat.map=new T.CanvasTexture(snapshot);textileMat.map.colorSpace=T.SRGBColorSpace;textileMat.needsUpdate=true;clothCompleted=true;lastStage=-1;target=1;autoFlight=false});
function reset(){target=progress=0;autoFlight=false;playing=true;el('pause').textContent='暂停';burst=0;el('scrub').value=0;reopenLetter();pavilion?.reset()}
const restartConfirm=document.createElement('dialog');restartConfirm.id='restart-confirm';restartConfirm.innerHTML='<h2>重新开始？</h2><p>重新开始会清空手记中的六段记忆和当前工艺进度。是否继续？</p><div><button id="restart-cancel">取消</button><button id="restart-clear">清空并重新开始</button></div>';document.body.append(restartConfirm);
function askToRestart(event){event?.preventDefault();restartConfirm.showModal()}
restartConfirm.querySelector('#restart-cancel').onclick=()=>restartConfirm.close();
restartConfirm.querySelector('#restart-clear').onclick=()=>{restartConfirm.close();document.querySelectorAll('dialog[open]').forEach(dialog=>dialog.close());resetJourney();dispatchEvent(new Event('story-restart'));reset();el('cover').hidden=false;el('cover').classList.remove('is-leaving')};
el('home').onclick=askToRestart;el('replay').onclick=askToRestart;el('pause').onclick=()=>{playing=!playing;el('pause').textContent=playing?'暂停':'继续'};el('scrub').oninput=e=>{target=+e.target.value/1000;autoFlight=false};
el('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{el('fullscreen').textContent='请在浏览器打开全屏'}};
renderer.domElement.addEventListener('pointermove',e=>{const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);mx=pointer.x;my=pointer.y;raycaster.setFromCamera(pointer,camera);const hits=raycaster.intersectObjects(pickTargets);hover=hits.length?hits[0].object.userData.plant:-1;renderer.domElement.style.cursor=hover>=0?'pointer':'grab'});
renderer.domElement.addEventListener('pointerdown',e=>{const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);raycaster.setFromCamera(pointer,camera);if(pavilion.group.visible&&raycaster.intersectObject(pavilion.group,true).length){pavilion.launch();return}const hits=raycaster.intersectObjects(pickTargets,true).filter(h=>{for(let o=h.object;o;o=o.parent)if(!o.visible)return false;return true});if(hits.length){const fishHit=hits.find(h=>{for(let o=h.object;o;o=o.parent)if(o.userData.memory==='fish')return true;return false;});let o=(fishHit||hits[0]).object,key;while(o&&!key){key=o.userData.memory;if(o.userData.plant!==undefined)key='flower';o=o.parent}if(key){dispatchEvent(new CustomEvent('open-memory',{detail:key}));return}}if(progress<.5){target=Math.min(.48,target+.12);burst=1}});
function explorationLocked(){return pavilion.flying||!el('cover').hidden||Boolean(document.querySelector('dialog[open]'));}
renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();if(explorationLocked())return;autoFlight=false;target=clamp(target+e.deltaY*.0002,.08,.42)},{passive:false});
addEventListener('keydown',e=>{if(e.target instanceof HTMLInputElement||explorationLocked())return;if(['ArrowRight','ArrowDown','ArrowLeft','ArrowUp'].includes(e.code)){e.preventDefault();target=clamp(target+(['ArrowRight','ArrowDown'].includes(e.code)?.06:-.06),.08,.42);autoFlight=false;}});
function resize(){const r=el('world').getBoundingClientRect();renderer.setSize(r.width,r.height);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(el('world'));resize();
paintScene(scene);
const pavilion=createPavilion(scene);
// Only this click-driven flock owns the flight camera. Legacy scroll flight
// values remain capped below their first activation threshold (.46).
addEventListener('pavilion-flight',()=>{target=progress;autoFlight=false;previewing=false;exploreTip.hidden=true;});
renderer.domElement.addEventListener('pointerdown',e=>{if(explorationLocked()){e.stopImmediatePropagation();}},true);
const flightVeil=document.createElement('div');flightVeil.className='flight-veil';document.body.append(flightVeil);
const workshopTransition=document.createElement('div');workshopTransition.className='workshop-transition';workshopTransition.hidden=true;workshopTransition.setAttribute('role','status');workshopTransition.textContent='你已经找到六段记忆。现在，把它们带回外婆留下的白布。';document.body.append(workshopTransition);
const journeyUiStyle=document.createElement('style');journeyUiStyle.textContent='.workshop-transition{position:fixed;inset:0;z-index:40;display:grid;place-items:center;padding:10vw;background:#071e31df;color:#f5ecd5;font:clamp(24px,4vw,52px)/1.45 serif;text-align:center}.workshop-transition[hidden]{display:none}#restart-confirm{max-width:min(560px,90vw);padding:30px;background:#f3ecd8;color:#173f53;border:1px solid #98754a}#restart-confirm::backdrop{background:#071c2bba}#restart-confirm div{display:flex;gap:12px;flex-wrap:wrap}';document.head.append(journeyUiStyle);
addEventListener('pavilion-flight-complete',()=>{workshopTransition.hidden=false;setTimeout(()=>{workshopTransition.hidden=true;dispatchEvent(new Event('open-workshop'))},reduced?800:2500)});
const updateFlightTransition=createFlightTransition();
const exploreTip=document.createElement('div');exploreTip.className='explore-tip';exploreTip.hidden=true;document.body.append(exploreTip);
const memoryNames={vine:'藤蔓与露珠 · 点击观察',tree:'古树 · 点击触摸记忆',village:'晾布的巷子 · 点击观察',flower:'花朵 · 点击观察',stream:'溪水 · 点击听故事',fish:'游鱼 · 点击观察',butterfly:'蝴蝶 · 点击观察',bird:'鸟 · 点击听故事'};
renderer.domElement.addEventListener('pointermove',e=>{if(pavilion.flying){exploreTip.hidden=true;return;}raycaster.setFromCamera(pointer,camera);let label='';if(pavilion.group.visible&&raycaster.intersectObject(pavilion.group,true).length)label='晾晒的蓝布 · 集齐手记后放飞';else{for(const hit of raycaster.intersectObjects(pickTargets,true)){let valid=true;for(let o=hit.object;o;o=o.parent)if(!o.visible)valid=false;if(!valid)continue;let key;for(let o=hit.object;o&&!key;o=o.parent)key=o.userData.plant!==undefined?'flower':o.userData.memory;if(key){label=memoryNames[key]||'点击观察';break;}}}exploreTip.hidden=!label;exploreTip.textContent=label;exploreTip.style.left=Math.max(8,Math.min(innerWidth-230,e.clientX+16))+'px';exploreTip.style.top=Math.max(8,Math.min(innerHeight-60,e.clientY+18))+'px';if(label)renderer.domElement.style.cursor='pointer';});
renderer.domElement.addEventListener('pointerleave',()=>exploreTip.hidden=true);
renderer.domElement.addEventListener('pointerdown',()=>exploreTip.hidden=true);
el('enter-world').onclick=()=>{birdEntryStart=elapsed;el('cover').classList.add('is-leaving');setTimeout(()=>{el('cover').hidden=true;target=.18},650)};
renderer.domElement.addEventListener('pointermove',e=>{const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);raycaster.setFromCamera(pointer,camera);if(pavilion.group.visible&&raycaster.intersectObject(pavilion.group,true).length)renderer.domElement.style.cursor='pointer'});
sun.visible=false;
document.querySelectorAll('.act-toggle').forEach(o=>o.remove());
addEventListener('story-restart',()=>pavilion.reset());
addEventListener('pavilion-return',()=>pavilion.reset());
function handleJourneyAction(){
 if(!el('cover').hidden||document.querySelector('dialog[open]'))return;
 if(pavilion.flying)return;
 if(progress>=.9){dispatchEvent(new Event('open-workshop'));return;}
 playing=true;el('pause').textContent='暂停';
 if(pavilion.group.visible){pavilion.launch();return;}
 target=Math.max(target,.18);burst=1;
}
el('action').addEventListener('click',handleJourneyAction);
giantBird.visible=false;
const preview=document.createElement('button');preview.className='painted-preview';preview.textContent='播放入山与风起';el('experience').append(preview);
let previewing=false;
preview.onclick=()=>{previewing=!previewing;if(previewing){target=progress=0;playing=true;autoFlight=false;preview.textContent='停止镜头';}else preview.textContent='播放入山与风起'};
const startColor=new T.Color('#f6e5cf'),endColor=new T.Color('#126798'),fogStart=new T.Color('#accbc6'),fogEnd=new T.Color('#367faa');
function updateText(stage){if(stage===lastStage)return;lastStage=stage;dispatchEvent(new CustomEvent('journey-stage',{detail:stage}));const titles=['外婆让你，先去看看山。','花展开了，布上的空白有了回答。','鸟飞过溪水，你记住了归途。','你把山野，带回了外婆的布上。'];const text=['你沿着旧路走进林间。手记里的花还没有画完。先停下来，看一看它怎样从根部伸展，又怎样把花瓣交给风。','花枝相连，把一次开放续成下一次生长。你没有摘花，只记住叶片的走向——回到工坊，蜡刀便知道该从哪里落下。','外婆画过的鸟，总与花枝和水里的鱼彼此照应。你顺着它的方向望去：远行与归来，原来可以留在同一块布上。','热水带走蜂蜡，白线从蓝里显出。花与鸟在布上重新相遇，外婆留出的空白有了你的回答。原来，回家的路可以穿在身上。'];if(stage===3&&!clothCompleted){titles[3]='还有半块白布，在等你回家。';text[3]='你记住了花枝与鸟的方向。现在回到外婆的木桌，拿起蜡刀，把这些相遇留进她未画完的空白。'}el('title').textContent=titles[stage];el('copy').textContent=text[stage];el('action').innerHTML=['停下来，观察花开','记住花的形，跟随鸟','带着记忆，回到布上','回工坊，亲手完成白布'][stage]+' <span aria-hidden="true">→</span>';el('stage-name').textContent=['入山','拾纹','归途','成布'][stage];el('chapter-label').textContent=['外婆的白布 · 入山','山野拾纹 · 花','山野拾纹 · 鸟','靛蓝显纹 · 回家'][stage];el('invitation').textContent=stage===0?'轻触花朵，记住它舒展的形状':'花留在山里，记忆带回布上';el('invitation').style.opacity=stage<2?'1':'0';document.body.classList.toggle('flying',stage>=2)}
function animate(now){requestAnimationFrame(animate);const dt=Math.min((now-last)/1000,.05);last=now;if(document.hidden)return;target=clamp(target,0,.42);progress=clamp(progress,0,.42);autoFlight=false;shock=Math.max(0,shock-dt*.65);if(playing){elapsed+=dt;if(!pavilion.flying)progress+=(target-progress)*(1-Math.exp(-dt*4));burst=Math.max(0,burst-dt*.6)}const p=progress,f=0,bank=0;updateText(p<.16?0:1);if(document.activeElement!==el('scrub'))el('scrub').value=Math.round(p*1000);
scene.background.copy(startColor).lerp(endColor,f);scene.fog.color.copy(fogStart).lerp(fogEnd,f);earth.position.y=-f*30;earth.visible=f<.998;sky.visible=f>.005;sky.position.y=0;const tablePhase=1;tableScene.visible=false;
const flight=smooth((p-.58)/.18),stormPower=smooth((p-.67)/.12)*(1-smooth((p-.9)/.08));storm.visible=stormPower>.002;stormPieces.forEach((x,i)=>{x.o.position.copy(x.base);x.o.position.x+=Math.sin(elapsed*x.speed+i)*6*stormPower;x.o.position.y+=Math.cos(elapsed*x.speed*1.6+i)*3*stormPower;x.o.rotation.z+=elapsed*x.speed*.6;x.o.material.opacity=.12+stormPower*.64});birdLine.opacity=stormPower*.9;giantBird.rotation.z=Math.sin(elapsed*.7)*.12;giantBird.scale.setScalar(2.4+stormPower*.35);
const portrait=camera.aspect<1;const worldEye=new T.Vector3(mix(0,1.5,bank)+(reduced?0:mx*.55)+Math.sin(elapsed*30)*stormPower*.12,mix(portrait?8:6.5,8,f)+Math.cos(elapsed*24)*stormPower*.08,mix(portrait?24:18,18,f)-p*4*(1-f)-flight*3);const worldLook=new T.Vector3(mix(0,0,f),mix(1,6,f)+(reduced?0:my*.18),mix(-9,-7,f)-flight*7);const tableEye=new T.Vector3((reduced?0:mx*.35),12.5,8.2),tableLook=new T.Vector3(0,.7,-1);camera.position.copy(tableEye.clone().lerp(worldEye,tablePhase));camera.up.set(-bank*.32,1,0).normalize();camera.lookAt(tableLook.clone().lerp(worldLook,tablePhase));
plants.forEach(o=>{const g=smooth((p*2.8-o.offset)*1.45);o.root.scale.y=Math.max(.065,g);o.root.scale.x=o.root.scale.z=.7+.3*g;o.root.rotation.z=(reduced?0:Math.sin(elapsed*1.2+o.index)*.028)*g;o.leafGroups.forEach((l,k)=>{const a=smooth((g-.17-k*.075)*2.7);l.scale.setScalar(Math.max(.015,a));l.rotation.x=(1-a)*1.4});const bloom=smooth((g-.43)*2.1);o.bloom.scale.setScalar(Math.max(.025,bloom+(o.index===hover?.12:0)));o.petals.forEach((w,j)=>{w.rotation.x=.1+smooth((g-.5)*2.4)*1.08;w.rotation.z=Math.sin(j)*.05})});
birds.forEach((o,i)=>{const flutter=reduced?0:Math.sin(elapsed*(i?4.7:3.6)+o.offset);for(const w of o.wings)w.rotation.z=w.userData.side*(.1+flutter*.55);if(i===0){o.b.position.set(.2+Math.sin(elapsed*.35)*.4,6.4+Math.sin(elapsed*.7)*.16,3);o.b.rotation.set(-.12,-.13,-.15+Math.sin(elapsed*.38)*.16);o.b.scale.setScalar((portrait?1.15:1.8)*smooth((f-.05)*2))}else{o.b.position.set(o.base.x+Math.sin(elapsed*.2+o.offset),6+o.base.y,(o.base.z+elapsed*(playing?1:0))%28-15);o.b.rotation.set(0,-.1,-.3);o.b.scale.setScalar(.5+(i%4)*.16)}});
glintMat.opacity=Math.min(.95,f*.42+shock*.4);glints.position.set(0,6,0);if(playing&&!reduced){const a=glintGeo.attributes.position;for(let i=0;i<280;i++){let j=i*6;for(let k=0;k<2;k++){a.array[j+k*3]-=dt*2;a.array[j+k*3+1]-=dt*5;a.array[j+k*3+2]+=dt*9}if(a.array[j+2]>20){a.array[j]+=20;a.array[j+1]+=35;a.array[j+2]-=70;a.array[j+3]=a.array[j]+.22;a.array[j+4]=a.array[j+1]+.6;a.array[j+5]=a.array[j+2]-.6}}a.needsUpdate=true}
const ending=smooth((p-.87)/.12);textile.visible=clothCompleted&&ending>.001;textileMat.opacity=ending;textile.position.set(0,6,1);textile.scale.setScalar((portrait?.52:.72)*(.85+ending*.15));textile.scale.x*=1.6875;textile.rotation.set(-.08*(1-ending),-.08*Math.sin(elapsed*.4),.06*(1-ending));const clothPos=textileGeo.attributes.position;for(let i=0;i<clothPos.count;i++){const k=i*3;clothPos.setZ(i,Math.sin(textileBase[k]*2+elapsed*.7)*.09+Math.sin(textileBase[k+1]*1.3+elapsed*.3)*.12)}clothPos.needsUpdate=true;sky.scale.setScalar(1-ending*.85);sky.position.y=-ending*5;
fishSchool.forEach((o,i)=>{const phase=elapsed*.16+i*.55,u=.17+.055*(1+Math.sin(phase));const point=riverPath.getPoint(u),tangent=riverPath.getTangent(u),normal=new T.Vector3(-tangent.z,0,tangent.x);o.position.copy(point).addScaledVector(normal,Math.sin(elapsed*.7+i)*.38);o.position.y=.02;o.rotation.y=Math.atan2(-tangent.x,-tangent.z)+(Math.cos(phase)<0?Math.PI:0)+Math.sin(elapsed*4+i)*.08;const tail=o.children[o.children.length-2];tail.rotation.y=Math.sin(elapsed*6+i)*.3;});
ripples.forEach(o=>{const flow=o.userData.flow,u=(flow.u+(reduced?0:elapsed*.018))%1,point=riverPath.getPoint(u),tangent=riverPath.getTangent(u);o.position.set(point.x-tangent.z*flow.offset,.375,point.z+tangent.x*flow.offset);o.rotation.z=Math.atan2(tangent.x,tangent.z);});butterflies.forEach((o,i)=>{const entry=smooth((elapsed-birdEntryStart-1-i*.4)/4);o.b.position.set(mix(10,4.3+i*.48,entry)+Math.sin(elapsed*.6+i)*.42,1.55+Math.sin(elapsed*.9+i)*.22,1.8-i*1.5);o.b.rotation.y=-.4;for(const w of o.wings)w.rotation.y=w.userData.side*Math.sin(elapsed*5+i)*.65});const birdEntry=smooth((elapsed-birdEntryStart)/4.5);perched.b.position.set(mix(-12,-3.8,birdEntry)+Math.sin(elapsed*.55)*.28,3.25+Math.sin(elapsed*.8)*.12,-1);perched.b.rotation.y=-.9;perched.wings.forEach(w=>w.rotation.z=w.userData.side*(.45+(reduced?0:Math.sin(elapsed*5)*.45)));waterMaterial.uniforms.time.value=reduced?0:elapsed;
pavilion.group.visible=p<.58||pavilion.flying;pavilion.update(elapsed,playing?dt:0,reduced);pavilion.group.visible=p<.58||pavilion.flying;el('action').disabled=pavilion.flying;if(pavilion.flying){el('title').textContent='鸟从布上醒来，飞向山野。';el('copy').textContent='一只鸟带起另一只鸟，蜡染里的花与水也跟着舒展。抬头，跟随它们的方向。';el('action').textContent='鸟群正在飞向蓝布…'}else if(p<.58){el('title').textContent='远处的染亭，正在晾晒山野。';el('copy').textContent='两个人在亭中点蜡，蓝布随风轻轻起伏。移动鼠标观看山谷，收集六段山野记忆，再轻触亭中的蓝布，让鸟群带你继续。';el('action').textContent='轻触蓝布，继续旅程 →';el('chapter-label').textContent='山野 · 染亭'}
const flightFrame=updateFlightTransition(pavilion.flightTime,pavilion.flying,reduced);flightVeil.style.opacity=flightFrame.veil;
if(pavilion.flying)aimPavilionCamera(camera,pavilion.flightTime,reduced);
updateLandmarks(reduced?0:elapsed);renderer.render(scene,camera)}
requestAnimationFrame(animate);window.addEventListener('error',()=>el('error').hidden=false);
